trigger:
  branches:
    include:
      - feature-ms-javierHormazabal-finaliza-el-curso-devops-foundation-v4

pr:
  branches:
    include:
      - '*'

variables:
  dockerRegistry: 'Docker'
  dockerImageName: 'your-docker-image-name'



stages:
- stage: Build
  displayName: 'Build and Analyze'
  jobs:
  - job: Build
    displayName: 'Build and Analyze'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      submodules: true

    - task: Gradle@2
      displayName: 'Build with Gradle'
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'clean build'

    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build jacocoTestReport jacocoTestCoverageVerification'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test/jacocoTestReport.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
        reportDirectory: '$(System.DefaultWorkingDirectory)/build/reports/jacoco/test'
        failIfCoverageEmpty: true
      displayName: 'Resultado Cobertura Codigo'

    - task: SonarCloudPrepare@1
      displayName: 'Prepare analysis on SonarCloud'
      inputs:
        SonarCloud: 'azuredevopslab'
        organization: 'genzodeveloper'
        projectKey: 'genzodeveloper_microservicio-spring'
        projectName: 'microservicio-spring'

- stage: Containerize
  displayName: 'Containerize'
  jobs:
  - job: BuildDockerImage
    displayName: 'Build Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        containerRegistry: 'Docker'
        repository: 'javierhormazabal/repository_labfinal'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'

- stage: Deploy
  displayName: 'Deploy to Kubernetes'
  jobs:
  - job: DeployToKubernetes
    displayName: 'Deploy to Kubernetes'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: KubernetesManifest@0
      displayName: 'Deploy to Kubernetes cluster'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: 'your-kubernetes-service-connection'
        manifests: |
          $(System.DefaultWorkingDirectory)/kubernetes-deployment.yaml
        namespace: 'your-kubernetes-namespace'
