pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'azuredevopslab'
    organization: 'genzodeveloper'
    scannerMode: 'MSBuild'
    projectKey: 'genzodeveloper_microservicio-spring'
    projectName: 'microservicio-spring'
  displayName: 'SonarCloud Prepare'


- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.5.0.2730'
    spotBugsAnalysis: false


- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'aibarra17/springpet-clinic'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'aibarra17/springpet-clinic'
    command: 'build'
    Dockerfile: '/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'aibarra17/springpet-clinic'
    command: 'push'